---
# Install desired apps

- name: "Install apps"
  include_tasks: "{{ playbook_root_dir }}/roles/tools/tasks/run_install/run_install.yml"
  loop: "{{ apps }}"
  loop_control:
    loop_var: app
  when: apps is defined
