---
# Run post install for alacritty

# Recommended post install:
# sudo cp target/release/alacritty /usr/local/bin # or anywhere else in $PATH
# sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
# sudo desktop-file-install extra/linux/Alacritty.desktop
# sudo update-desktop-database

- name: "Symbolic link alacritty to /usr/local/bin"
  become: true
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.cargo/bin/alacritty"
    dest: /usr/local/bin/alacritty
    state: link
- name: "Install alacritty desktop file"
  become: true
  ansible.builtin.command: "desktop-file-install {{ ansible_env.HOME }}/.dotfiles/ansible/roles/tools/tasks/files/alacritty.desktop"
  when: true
- name: "Update desktop database"
  become: true
  ansible.builtin.command: "update-desktop-database"
  when: true
