---
# Run post install for docker

- name: "Get user name for docker group"
  ansible.builtin.shell: "echo $USER"
  register: user_name
  when: true
- name: "Add user to docker group"
  become: true
  ansible.builtin.user:
    name: "{{ user_name.stdout }}"
    groups: docker
    append: true
- name: "Enable docker service"
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
